import { randomUUID } from 'node:crypto';
import { verifyPassword, issueAccessToken, newRefreshToken, hashRefreshToken, REFRESH_TTL_SECONDS, hashPassword } from '../auth.js';
import { newId, nowIso } from '../db.js';
import { resolve } from '../permissions.js';
import { send, badRequest, unauthenticated, conflict, notFound } from '../http.js';

const cookie=(token,maxAge)=>`rt=${token}; Max-Age=${maxAge}; Path=/v1/auth/refresh; HttpOnly; SameSite=Strict; Secure`;
function orgsFor(db,userId){ return db.prepare(`SELECT o.id,o.name,o.theme,m.role,m.status FROM memberships m JOIN organizations o ON o.id=m.org_id WHERE m.user_id=? AND m.status!='removed' AND o.deleted_at IS NULL ORDER BY o.name`).all(userId); }
function issue(db,userId,orgId,secret){ const m=db.prepare('SELECT * FROM memberships WHERE user_id=? AND org_id=?').get(userId,orgId); if(!m||m.status==='removed') throw notFound(); return issueAccessToken({userId,orgId,role:m.role,permVersion:m.perm_version},secret); }
function createRefresh(db,userId){ const raw=newRefreshToken(), family=randomUUID(); db.prepare('INSERT INTO refresh_tokens (id,user_id,token_hash,family_id,expires_at) VALUES (?,?,?,?,?)').run(newId('rt'),userId,hashRefreshToken(raw),family,new Date(Date.now()+REFRESH_TTL_SECONDS*1000).toISOString()); return raw; }
export function register(router,{db,secret}){
 router.post('/v1/auth/login',(ctx,_p,res)=>{ const email=String(ctx.body.email??'').trim().toLowerCase(), password=String(ctx.body.password??''); if(!email||!password) throw badRequest('email and password are required'); const u=db.prepare('SELECT * FROM users WHERE email=?').get(email); if(!u||!verifyPassword(password,u.password_hash)) throw unauthenticated('invalid email or password'); const memberships=orgsFor(db,u.id); if(!memberships.length) throw unauthenticated('invalid email or password'); const requested=ctx.body.orgId; const org=requested?memberships.find(m=>m.id===requested):memberships[0]; if(!org) throw notFound(); const token=issueAccessToken({userId:u.id,orgId:org.id,role:org.role,permVersion:db.prepare('SELECT perm_version FROM memberships WHERE user_id=? AND org_id=?').get(u.id,org.id).perm_version},secret); const rt=createRefresh(db,u.id); res.setHeader('Set-Cookie',cookie(rt,REFRESH_TTL_SECONDS)); send(res,200,{token,user:{id:u.id,email:u.email,name:u.name},role:org.role,org:{id:org.id,name:org.name,theme:org.theme},orgs:memberships}); });
 router.post('/v1/auth/token',(ctx,_p,res)=>{ const orgId=String(ctx.body.orgId??''); const m=db.prepare(`SELECT m.*,o.name,o.theme FROM memberships m JOIN organizations o ON o.id=m.org_id WHERE m.user_id=? AND m.org_id=? AND m.status='active' AND o.deleted_at IS NULL`).get(ctx.userId,orgId); if(!m) throw notFound(); send(res,200,{token:issueAccessToken({userId:ctx.userId,orgId,role:m.role,permVersion:m.perm_version},secret),role:m.role,org:{id:orgId,name:m.name,theme:m.theme}}); });
 router.post('/v1/auth/me',(ctx,_p,res)=>send(res,200,{}));
 router.get('/v1/auth/me',(ctx,_p,res)=>{ const u=db.prepare('SELECT id,email,name FROM users WHERE id=?').get(ctx.userId); const org=db.prepare('SELECT id,name,theme FROM organizations WHERE id=?').get(ctx.orgId); send(res,200,{user:u,role:ctx.role,org,orgs:orgsFor(db,ctx.userId),permissions:resolve(db,{userId:ctx.userId,orgId:ctx.orgId}).permissions}); });
 router.post('/v1/auth/refresh',(ctx,_p,res)=>{ const raw=(ctx.req.headers.cookie??'').split(';').map(x=>x.trim()).find(x=>x.startsWith('rt='))?.slice(3); if(!raw) throw unauthenticated('missing refresh token'); const row=db.prepare('SELECT * FROM refresh_tokens WHERE token_hash=?').get(hashRefreshToken(raw)); if(!row){ const h=hashRefreshToken(raw); const old=db.prepare('SELECT family_id FROM refresh_tokens WHERE token_hash=?').get(h); if(old) db.prepare('UPDATE refresh_tokens SET revoked_at=? WHERE family_id=? AND revoked_at IS NULL').run(nowIso(),old.family_id); throw unauthenticated('invalid refresh token'); } if(row.revoked_at||row.expires_at<=nowIso()){ if(row.revoked_at) db.prepare('UPDATE refresh_tokens SET revoked_at=? WHERE family_id=? AND revoked_at IS NULL').run(nowIso(),row.family_id); throw unauthenticated('invalid refresh token'); } db.prepare('UPDATE refresh_tokens SET revoked_at=? WHERE id=?').run(nowIso(),row.id); const m=db.prepare("SELECT * FROM memberships WHERE user_id=? AND status='active' ORDER BY created_at LIMIT 1").get(row.user_id); if(!m) throw unauthenticated('invalid refresh token'); const rt=createRefresh(db,row.user_id); res.setHeader('Set-Cookie',cookie(rt,REFRESH_TTL_SECONDS)); send(res,200,{token:issueAccessToken({userId:m.user_id,orgId:m.org_id,role:m.role,permVersion:m.perm_version},secret)}); });
}
