import { newId, nowIso } from '../db.js';
import { send, badRequest, notFound, forbidden } from '../http.js';
import { assertCan, resolveDevices } from '../permissions.js';
import { audit, auditDenials } from '../audit.js';
import { endActiveSessions } from '../lifecycle.js';
function get(db,org,id){return db.prepare("SELECT * FROM devices WHERE id=? AND org_id=? AND deleted_at IS NULL").get(id,org)}
export function register(router,{db}){
 router.get('/v1/orgs/:org/devices',(ctx,p,res)=>{auditDenials(db,ctx,{action:'device.list',targetType:'org',targetId:p.org},()=>assertCan(db,ctx,'device:list'));const rows=db.prepare('SELECT id,name,kind,online FROM devices WHERE org_id=? AND deleted_at IS NULL ORDER BY name').all(p.org);const ids=rows.map(r=>r.id),r=resolveDevices(db,{userId:ctx.userId,orgId:p.org,deviceIds:ids});send(res,200,{devices:rows.filter(d=>r.byDevice[d.id]['device:view']?.effect==='allow').map(d=>({...d,online:Boolean(d.online),permissions:r.byDevice[d.id]}))});});
 router.get('/v1/orgs/:org/devices/:id',(ctx,p,res)=>{const d=get(db,p.org,p.id);if(!d)throw notFound();assertCan(db,ctx,'device:view',p.id);const r=resolveDevices(db,{userId:ctx.userId,orgId:p.org,deviceIds:[p.id]}).byDevice[p.id];send(res,200,{...d,online:Boolean(d.online),permissions:r});});
 router.post('/v1/orgs/:org/devices',(ctx,p,res)=>{assertCan(db,ctx,'device:provision');const name=String(ctx.body.name??'').trim(),kind=String(ctx.body.kind??'');if(!name||!['macos','windows','linux','android','ios'].includes(kind))throw badRequest('name and valid kind are required');const id=newId('dev');db.prepare('INSERT INTO devices (id,org_id,name,kind,online) VALUES (?,?,?,?,?)').run(id,p.org,name,kind,0);audit(db,{orgId:p.org,actorId:ctx.userId,action:'device.provision',targetType:'device',targetId:id,result:'allow',requestId:ctx.requestId});send(res,201,{id,name,kind,online:false});});
 router.patch('/v1/orgs/:org/devices/:id',(ctx,p,res)=>{auditDenials(db,ctx,{action:'device.update',targetType:'device',targetId:p.id},()=>assertCan(db,ctx,'device:update',p.id));const d=get(db,p.org,p.id);if(!d)throw notFound();const name=String(ctx.body.name??d.name).trim();db.prepare('UPDATE devices SET name=? WHERE id=?').run(name,p.id);audit(db,{orgId:p.org,actorId:ctx.userId,action:'device.update',targetType:'device',targetId:p.id,result:'allow',requestId:ctx.requestId});send(res,200,{...d,name});});
 router.delete('/v1/orgs/:org/devices/:id',(ctx,p,res)=>{auditDenials(db,ctx,{action:'device.delete',targetType:'device',targetId:p.id},()=>assertCan(db,ctx,'device:provision',p.id));if(!get(db,p.org,p.id))throw notFound();db.prepare('UPDATE devices SET deleted_at=? WHERE id=?').run(nowIso(),p.id);endActiveSessions(db,{orgId:p.org,deviceId:p.id,reason:'device_transferred'});audit(db,{orgId:p.org,actorId:ctx.userId,action:'device.delete',targetType:'device',targetId:p.id,result:'allow',requestId:ctx.requestId});send(res,204);});
 router.post('/v1/orgs/:org/devices/:id/transfer',(ctx,p,res)=>{assertCan(db,ctx,'device:provision',p.id);const d=get(db,p.org,p.id),dest=String(ctx.body.orgId??'');if(!d)throw notFound();if(!db.prepare('SELECT 1 FROM organizations WHERE id=? AND deleted_at IS NULL').get(dest))throw notFound();const target=db.prepare("SELECT * FROM memberships WHERE org_id=? AND user_id=? AND status='active'").get(dest,ctx.userId);if(!target)throw notFound();const destPerm=resolveDevices(db,{userId:ctx.userId,orgId:dest,deviceIds:[p.id]}).byDevice[p.id]?.['device:provision'];if(destPerm?.effect!=='allow')throw forbidden('missing permission: device:provision','missing_permission');db.prepare('UPDATE devices SET org_id=? WHERE id=?').run(dest,p.id);endActiveSessions(db,{orgId:p.org,deviceId:p.id,reason:'device_transferred'});audit(db,{orgId:p.org,actorId:ctx.userId,action:'device.transfer',targetType:'device',targetId:p.id,result:'allow',requestId:ctx.requestId});send(res,200,{id:p.id,orgId:dest});});
}
