import { newId, nowIso, bumpPermVersion } from '../db.js';
import { newInviteToken, hashInviteToken, hashPassword } from '../auth.js';
import { send, badRequest, notFound, conflict, gone, forbidden } from '../http.js';
import { assertCan, assertMayGrant } from '../permissions.js';
import { assertCanModify } from '../lifecycle.js';
import { audit, auditDenials } from '../audit.js';
export function register(router,{db}){
 router.post('/v1/orgs/:org/invites',(ctx,p,res)=>{auditDenials(db,ctx,{action:'invite.create',targetType:'org',targetId:p.org},()=>assertCan(db,ctx,'user:invite'));const email=String(ctx.body.email??'').trim().toLowerCase(),role=String(ctx.body.role??'');if(!email||!role)throw badRequest('email and role are required');if(!db.prepare('SELECT 1 FROM roles WHERE key=?').get(role))throw badRequest('unknown role');const rank=db.prepare('SELECT rank FROM roles WHERE key=?').get(role).rank, cr=db.prepare('SELECT rank FROM roles WHERE key=?').get(ctx.role).rank;if(rank>cr)throw forbidden('role cannot be assigned','forbidden');if(db.prepare("SELECT 1 FROM memberships WHERE org_id=? AND user_id=(SELECT id FROM users WHERE email=?) AND status='active'").get(p.org,email))throw conflict('user already belongs to this org');if(db.prepare('SELECT 1 FROM invites WHERE org_id=? AND email=? AND accepted_at IS NULL AND revoked_at IS NULL').get(p.org,email))throw conflict('invite already exists');const raw=newInviteToken(),id=newId('inv');db.prepare('INSERT INTO invites (id,org_id,email,role,token_hash,invited_by,expires_at) VALUES (?,?,?,?,?,?,?)').run(id,p.org,email,role,hashInviteToken(raw),ctx.userId,new Date(Date.now()+7*864e5).toISOString());audit(db,{orgId:p.org,actorId:ctx.userId,action:'invite.create',targetType:'invite',targetId:id,result:'allow',requestId:ctx.requestId});send(res,201,{id,inviteToken:raw,email,role});});
 router.get('/v1/orgs/:org/invites',(ctx,p,res)=>{assertCan(db,ctx,'user:invite');const rows=db.prepare('SELECT id,email,role,expires_at,accepted_at,revoked_at,created_at FROM invites WHERE org_id=? ORDER BY created_at DESC').all(p.org);send(res,200,{invites:rows});});
 router.delete('/v1/orgs/:org/invites/:id',(ctx,p,res)=>{assertCan(db,ctx,'user:invite');const r=db.prepare('SELECT * FROM invites WHERE id=? AND org_id=? AND accepted_at IS NULL AND revoked_at IS NULL').get(p.id,p.org);if(!r)throw notFound();db.prepare('UPDATE invites SET revoked_at=? WHERE id=?').run(nowIso(),p.id);send(res,204);});
 router.get('/v1/invites/:token',(ctx,p,res)=>{const r=db.prepare(`SELECT i.*,o.name org_name FROM invites i JOIN organizations o ON o.id=i.org_id WHERE i.token_hash=?`).get(hashInviteToken(p.token));if(!r)throw notFound();if(r.revoked_at||r.accepted_at)throw conflict('invite already used');if(r.expires_at<=nowIso())throw gone();send(res,200,{orgName:r.org_name,role:r.role,email:r.email,expiresAt:r.expires_at});});
 router.post('/v1/invites/:token/accept',(ctx,p,res)=>{const r=db.prepare(`SELECT i.*,o.name org_name FROM invites i JOIN organizations o ON o.id=i.org_id WHERE i.token_hash=?`).get(hashInviteToken(p.token));if(!r)throw notFound();if(r.revoked_at||r.accepted_at)throw conflict('invite already used');if(r.expires_at<=nowIso())throw gone();const name=String(ctx.body.name??'').trim(),password=String(ctx.body.password??'');if(!name||password.length<8)throw badRequest('name and password (8+ characters) are required');let user=db.prepare('SELECT * FROM users WHERE email=?').get(r.email);const tx=db.transaction(()=>{if(!user){const id=newId('usr');db.prepare('INSERT INTO users (id,email,name,password_hash) VALUES (?,?,?,?)').run(id,r.email,name,hashPassword(password));user={id,email:r.email,name};}else db.prepare('UPDATE users SET name=? WHERE id=?').run(name,user.id);const m=db.prepare('SELECT * FROM memberships WHERE org_id=? AND user_id=?').get(r.org_id,user.id);if(m&&m.status!=='invited')throw conflict('membership already exists');if(m)db.prepare("UPDATE memberships SET role=?,status='active',perm_version=perm_version+1 WHERE id=?").run(r.role,m.id);else db.prepare("INSERT INTO memberships (id,org_id,user_id,role,status,invited_by,joined_at) VALUES (?,?,?,?,?,?,?)").run(newId('mem'),r.org_id,user.id,r.role,'active',r.invited_by,nowIso());db.prepare('UPDATE invites SET accepted_at=?,accepted_by=? WHERE id=?').run(nowIso(),user.id,r.id);});tx();send(res,200,{userId:user.id,role:r.role,email:r.email});});
}
