import { newId, nowIso, bumpPermVersion } from '../db.js';
import { send, badRequest, notFound, forbidden, selfRoleChange, conflict } from '../http.js';
import { assertCan, can, assertMayGrant, resolve } from '../permissions.js';
import { audit, auditDenials } from '../audit.js';
import { assertRoleExists, assertCanModify, assertNotLastOwner, endActiveSessions } from '../lifecycle.js';
import { normalizeTs } from '../http.js';

function org(db,id){return db.prepare("SELECT * FROM organizations WHERE id=? AND deleted_at IS NULL").get(id)}
function member(db,orgId,userId){return db.prepare("SELECT * FROM memberships WHERE org_id=? AND user_id=? AND status!='removed'").get(orgId,userId)}
export function register(router,{db}){
 router.get('/v1/orgs',(ctx,_p,res)=>send(res,200,{orgs:db.prepare("SELECT o.id,o.name,o.theme,m.role,m.status FROM memberships m JOIN organizations o ON o.id=m.org_id WHERE m.user_id=? AND m.status!='removed' AND o.deleted_at IS NULL ORDER BY o.name").all(ctx.userId)}));
 router.post('/v1/orgs',(ctx,_p,res)=>{const name=String(ctx.body.name??'').trim();if(!name)throw badRequest('name is required');const id=newId('org'),tx=db.transaction(()=>{db.prepare('INSERT INTO organizations (id,name,theme) VALUES (?,?,?)').run(id,name,'cobalt');db.prepare('INSERT INTO memberships (id,org_id,user_id,role,status) VALUES (?,?,?,?,?)').run(newId('mem'),id,ctx.userId,'owner','active');});tx();audit(db,{orgId:id,actorId:ctx.userId,action:'org.create',targetType:'org',targetId:id,result:'allow',requestId:ctx.requestId});send(res,201,{id,name,theme:'cobalt',role:'owner'});});
 router.patch('/v1/orgs/:org',(ctx,p,res)=>{auditDenials(db,ctx,{action:'org.update',targetType:'org',targetId:p.org},()=>assertCan(db,ctx,'org:update'));const o=org(db,p.org);if(!o)throw notFound();const name=String(ctx.body.name??'').trim();if(!name)throw badRequest('name is required');db.prepare('UPDATE organizations SET name=? WHERE id=?').run(name,p.org);audit(db,{orgId:p.org,actorId:ctx.userId,action:'org.update',targetType:'org',targetId:p.org,result:'allow',requestId:ctx.requestId});send(res,200,{id:p.org,name,theme:o.theme});});
 router.delete('/v1/orgs/:org',(ctx,p,res)=>{auditDenials(db,ctx,{action:'org.delete',targetType:'org',targetId:p.org},()=>assertCan(db,ctx,'org:delete'));if(!org(db,p.org))throw notFound();db.prepare('UPDATE organizations SET deleted_at=? WHERE id=?').run(nowIso(),p.org);audit(db,{orgId:p.org,actorId:ctx.userId,action:'org.delete',targetType:'org',targetId:p.org,result:'allow',requestId:ctx.requestId});send(res,204);});
 router.get('/v1/orgs/:org/members',(ctx,p,res)=>{assertCan(db,ctx,'user:read');if(!org(db,p.org))throw notFound();send(res,200,{members:db.prepare("SELECT u.id,u.email,u.name,m.role,m.status,m.joined_at,m.perm_version FROM memberships m JOIN users u ON u.id=m.user_id WHERE m.org_id=? AND m.status!='removed' ORDER BY u.name").all(p.org)});});
 router.patch('/v1/orgs/:org/members/:userId',(ctx,p,res)=>{auditDenials(db,ctx,{action:'member.role.update',targetType:'user',targetId:p.userId},()=>assertCan(db,ctx,'user:role:update'));const target=member(db,p.org,p.userId);if(!target)throw notFound();if(target.user_id===ctx.userId)throw selfRoleChange();const role=String(ctx.body.role??'');assertRoleExists(db,role);assertCanModify(db,ctx.role,role);if(target.role==='owner'&&role!=='owner')assertNotLastOwner(db,p.org,p.userId);db.prepare('UPDATE memberships SET role=?,perm_version=perm_version+1 WHERE org_id=? AND user_id=?').run(role,p.org,p.userId);audit(db,{orgId:p.org,actorId:ctx.userId,action:'member.role.update',targetType:'user',targetId:p.userId,result:'allow',requestId:ctx.requestId});send(res,200,{userId:p.userId,role});});
 router.post('/v1/orgs/:org/members/:userId/suspend',(ctx,p,res)=>changeStatus(db,ctx,p,'suspended',res));
 router.delete('/v1/orgs/:org/members/:userId/suspend',(ctx,p,res)=>changeStatus(db,ctx,p,'active',res));
 router.delete('/v1/orgs/:org/members/me',(ctx,p,res)=>{if(ctx.orgId!==p.org)throw notFound();assertNotLastOwner(db,p.org,ctx.userId);db.prepare("UPDATE memberships SET status='removed',perm_version=perm_version+1 WHERE org_id=? AND user_id=?").run(p.org,ctx.userId);endActiveSessions(db,{orgId:p.org,userId:ctx.userId,reason:'membership_removed'});audit(db,{orgId:p.org,actorId:ctx.userId,action:'member.leave',targetType:'user',targetId:ctx.userId,result:'allow',requestId:ctx.requestId});send(res,204);});
 router.delete('/v1/orgs/:org/members/:userId',(ctx,p,res)=>{auditDenials(db,ctx,{action:'member.remove',targetType:'user',targetId:p.userId},()=>assertCan(db,ctx,'user:remove'));const t=member(db,p.org,p.userId);if(!t)throw notFound();if(t.user_id===ctx.userId)throw forbidden('use leave endpoint');assertCanModify(db,ctx.role,t.role);if(t.role==='owner')assertNotLastOwner(db,p.org,p.userId);db.prepare("UPDATE memberships SET status='removed',perm_version=perm_version+1 WHERE org_id=? AND user_id=?").run(p.org,p.userId);endActiveSessions(db,{orgId:p.org,userId:p.userId,reason:'membership_removed'});audit(db,{orgId:p.org,actorId:ctx.userId,action:'member.remove',targetType:'user',targetId:p.userId,result:'allow',requestId:ctx.requestId});send(res,204);});
 router.get('/v1/orgs/:org/users/:userId/effective',(ctx,p,res)=>{if(ctx.userId!==p.userId)assertCan(db,ctx,'user:read');const t=member(db,p.org,p.userId);if(!t)throw notFound();send(res,200,resolve(db,{userId:p.userId,orgId:p.org}));});
 router.get('/v1/orgs/:org/audit',(ctx,p,res)=>{assertCan(db,ctx,'audit:read');if(!org(db,p.org))throw notFound();const limit=Math.min(200,Math.max(1,Number(ctx.query.get('limit')??50)));const events=db.prepare('SELECT * FROM audit_events WHERE org_id=? ORDER BY at DESC LIMIT ?').all(p.org,limit);send(res,200,{events});});
 router.get('/v1/orgs/:org/grants',(ctx,p,res)=>{assertCan(db,ctx,'user:read');if(!org(db,p.org))throw notFound();const rows=db.prepare(`SELECT g.*,u.email AS user_email FROM grants g JOIN users u ON u.id=g.user_id WHERE g.org_id=? AND g.revoked_at IS NULL ORDER BY g.created_at DESC`).all(p.org);for(const r of rows)r.permissions=db.prepare('SELECT permission FROM grant_permissions WHERE grant_id=?').all(r.id).map(x=>x.permission);send(res,200,{grants:rows});});
 router.post('/v1/orgs/:org/grants',(ctx,p,res)=>{auditDenials(db,ctx,{action:'grant.create',targetType:'user',targetId:String(ctx.body.userId??'')},()=>assertCan(db,ctx,'grant:create'));const userId=String(ctx.body.userId??''),deviceId=ctx.body.deviceId??null,effect=ctx.body.effect,permissions=Array.isArray(ctx.body.permissions)?[...new Set(ctx.body.permissions.map(String))]:[];if(!permissions.length)throw badRequest('permissions must not be empty');if(!['allow','deny'].includes(effect))throw badRequest('effect must be allow or deny');const t=member(db,p.org,userId);if(!t||t.status!=='active')throw notFound();if(deviceId!==null&&!db.prepare('SELECT 1 FROM devices WHERE id=? AND org_id=? AND deleted_at IS NULL').get(deviceId,p.org))throw notFound();ctx.targetUserId=userId;assertMayGrant(db,ctx,permissions,deviceId);const id=newId('grt');const starts=normalizeTs(ctx.body.startsAt,'startsAt'),expires=normalizeTs(ctx.body.expiresAt,'expiresAt');if(expires&&expires<=nowIso())throw badRequest('expiresAt is in the past','expired_grant');const tx=db.transaction(()=>{db.prepare('INSERT INTO grants (id,org_id,user_id,device_id,effect,starts_at,expires_at,created_by) VALUES (?,?,?,?,?,?,?,?)').run(id,p.org,userId,deviceId,effect,starts,expires,ctx.userId);const ins=db.prepare('INSERT INTO grant_permissions (grant_id,permission) VALUES (?,?)');for(const x of permissions){try{ins.run(id,x)}catch(e){if(String(e.code).includes('FOREIGNKEY'))throw badRequest(`unknown permission: ${x}`,'unknown_permission');throw e;}}bumpPermVersion(db,{orgId:p.org,userId});audit(db,{orgId:p.org,actorId:ctx.userId,action:'grant.create',targetType:'grant',targetId:id,result:'allow',requestId:ctx.requestId});});tx();send(res,201,{id,userId,deviceId,effect,permissions});});
 router.delete('/v1/orgs/:org/grants/:id',(ctx,p,res)=>{auditDenials(db,ctx,{action:'grant.revoke',targetType:'grant',targetId:p.id},()=>assertCan(db,ctx,'grant:revoke'));const g=db.prepare('SELECT * FROM grants WHERE id=? AND org_id=? AND revoked_at IS NULL').get(p.id,p.org);if(!g)throw notFound();db.prepare('UPDATE grants SET revoked_at=? WHERE id=?').run(nowIso(),p.id);bumpPermVersion(db,{orgId:p.org,userId:g.user_id});audit(db,{orgId:p.org,actorId:ctx.userId,action:'grant.revoke',targetType:'grant',targetId:p.id,result:'allow',requestId:ctx.requestId});send(res,204);});
}
function changeStatus(db,ctx,p,status,res){
  auditDenials(db,ctx,{action:status==='suspended'?'member.suspend':'member.reinstate',targetType:'user',targetId:p.userId},()=>assertCan(db,ctx,'user:remove'));
  const t=member(db,p.org,p.userId); if(!t) throw notFound(); if(t.user_id===ctx.userId) throw forbidden('cannot change your own status');
  assertCanModify(db,ctx.role,t.role); if(status==='suspended'&&t.role==='owner') assertNotLastOwner(db,p.org,p.userId);
  db.prepare('UPDATE memberships SET status=?,perm_version=perm_version+1 WHERE org_id=? AND user_id=?').run(status,p.org,p.userId);
  if(status==='suspended') endActiveSessions(db,{orgId:p.org,userId:p.userId,reason:'user_suspended'});
  audit(db,{orgId:p.org,actorId:ctx.userId,action:status==='suspended'?'member.suspend':'member.reinstate',targetType:'user',targetId:p.userId,result:'allow',requestId:ctx.requestId});
  send(res,200,{userId:p.userId,status});
}
